var $this = $('');
var start = $('');
var p = $("");
var s = $('');
var item = $('');
item.append($('' + dataAndEvents + ''));
item.append($('' + dataAndEvents + ''));
s.append(item);
s.append($(''));
s.append($('' + dataAndEvents + ''));
s.append($('' + deepDataAndEvents + ''));
s._append_();
p.append(s);
start.append(p);
$this.append(start);